// Copyright (c) Microsoft Open Technologies, Inc. All rights reserved. See License.txt in the project root for license information.
namespace Microsoft.DbContextPackage.Utilities
{
    using System.Collections.Generic;
    using System.Data.Entity.Design;
    using System.Linq;
    using System.Text;

    /// <summary>
    /// Generates the Views.cs (or Views.vb) file content from a flat dictionary of
    /// extent-name → eSQL view strings, without requiring the dynamic EF6 objects
    /// that the T4 templates normally iterate over.
    /// </summary>
    internal static class ViewsCodeGenerator
    {
        public static string GenerateCode(
            LanguageOption languageOption,
            string contextTypeName,
            string mappingHashValue,
            Dictionary<string, string> views)
        {
            DebugCheck.NotEmpty(contextTypeName);
            DebugCheck.NotEmpty(mappingHashValue);
            DebugCheck.NotNull(views);

            if (languageOption == LanguageOption.GenerateVBCode)
            {
                return GenerateVBCode(contextTypeName, mappingHashValue, views);
            }

            return GenerateCSharpCode(contextTypeName, mappingHashValue, views);
        }

        private static string GenerateCSharpCode(
            string contextTypeName,
            string mappingHashValue,
            Dictionary<string, string> views)
        {
            var sb = new StringBuilder();
            var sortedViews = views.OrderBy(v => v.Key).ToList();

            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by a tool.");
            sb.AppendLine("//");
            sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("//     the code is regenerated.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine("using System.Data.Entity.Infrastructure.MappingViews;");
            sb.AppendLine();
            sb.AppendLine("[assembly: DbMappingViewCacheTypeAttribute(");
            sb.Append("    typeof(").Append(contextTypeName).AppendLine("),");
            sb.Append("    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets")
                .Append(mappingHashValue).AppendLine("))]");
            sb.AppendLine();
            sb.AppendLine("namespace Edm_EntityMappingGeneratedViews");
            sb.AppendLine("{");
            sb.AppendLine("    using System;");
            sb.AppendLine("    using System.CodeDom.Compiler;");
            sb.AppendLine("    using System.Data.Entity.Core.Metadata.Edm;");
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Implements a mapping view cache.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    [GeneratedCode(\"Entity Framework 6 Power Tools\", \"0.9.5.0\")]");
            sb.Append("    internal sealed class ViewsForBaseEntitySets")
                .Append(mappingHashValue).AppendLine(" : DbMappingViewCache");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Gets a hash value computed over the mapping closure.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        public override string MappingHashValue");
            sb.AppendLine("        {");
            sb.Append("            get { return \"").Append(mappingHashValue).AppendLine("\"; }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Gets a view corresponding to the specified extent.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine("        /// <param name=\"extent\">The extent.</param>");
            sb.AppendLine("        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>");
            sb.AppendLine("        public override DbMappingView GetView(EntitySetBase extent)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (extent == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                throw new ArgumentNullException(\"extent\");");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            var extentName = extent.EntityContainer.Name + \".\" + extent.Name;");

            var index = 0;
            foreach (var view in sortedViews)
            {
                sb.AppendLine();
                sb.Append("            if (extentName == \"").Append(view.Key).AppendLine("\")");
                sb.AppendLine("            {");
                sb.Append("                return GetView").Append(index).AppendLine("();");
                sb.AppendLine("            }");
                index++;
            }

            sb.AppendLine();
            sb.AppendLine("            return null;");
            sb.AppendLine("        }");

            index = 0;
            foreach (var view in sortedViews)
            {
                sb.AppendLine();
                sb.AppendLine("        /// <summary>");
                sb.Append("        /// Gets the view for ").Append(view.Key).AppendLine(".");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        /// <returns>The mapping view.</returns>");
                sb.Append("        private static DbMappingView GetView").Append(index).AppendLine("()");
                sb.AppendLine("        {");
                sb.Append("            return new DbMappingView(@\"").Append(view.Value).AppendLine("\");");
                sb.AppendLine("        }");
                index++;
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        private static string GenerateVBCode(
            string contextTypeName,
            string mappingHashValue,
            Dictionary<string, string> views)
        {
            var sb = new StringBuilder();
            var sortedViews = views.OrderBy(v => v.Key).ToList();

            sb.AppendLine("'------------------------------------------------------------------------------");
            sb.AppendLine("' <auto-generated>");
            sb.AppendLine("'     This code was generated by a tool.");
            sb.AppendLine("'");
            sb.AppendLine("'     Changes to this file may cause incorrect behavior and will be lost if");
            sb.AppendLine("'     the code is regenerated.");
            sb.AppendLine("' </auto-generated>");
            sb.AppendLine("'------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine("Option Strict Off");
            sb.AppendLine("Option Explicit On");
            sb.AppendLine();
            sb.AppendLine("Imports System");
            sb.AppendLine("Imports System.CodeDom.Compiler");
            sb.AppendLine("Imports System.Data.Entity.Core.Metadata.Edm");
            sb.AppendLine("Imports System.Data.Entity.Infrastructure.MappingViews");
            sb.AppendLine();
            sb.AppendLine("<Assembly: DbMappingViewCacheTypeAttribute(");
            sb.Append("    GetType(").Append(contextTypeName).AppendLine("),");
            sb.Append("    GetType(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets")
                .Append(mappingHashValue).AppendLine("))>");
            sb.AppendLine();
            sb.AppendLine("Namespace Edm_EntityMappingGeneratedViews");
            sb.AppendLine();
            sb.AppendLine("    ''' <summary>");
            sb.AppendLine("    ''' Implements a mapping view cache.");
            sb.AppendLine("    ''' </summary>");
            sb.AppendLine("    <GeneratedCode(\"Entity Framework 6 Power Tools\", \"0.9.5.0\")>");
            sb.Append("    Friend NotInheritable Class ViewsForBaseEntitySets")
                .AppendLine(mappingHashValue);
            sb.AppendLine("        Inherits DbMappingViewCache");
            sb.AppendLine();
            sb.AppendLine("        ''' <summary>");
            sb.AppendLine("        ''' Gets a hash value computed over the mapping closure.");
            sb.AppendLine("        ''' </summary>");
            sb.AppendLine("        Public Overrides ReadOnly Property MappingHashValue As String");
            sb.AppendLine("            Get");
            sb.Append("                Return \"").Append(mappingHashValue).AppendLine("\"");
            sb.AppendLine("            End Get");
            sb.AppendLine("        End Property");
            sb.AppendLine();
            sb.AppendLine("        ''' <summary>");
            sb.AppendLine("        ''' Gets a view corresponding to the specified extent.");
            sb.AppendLine("        ''' </summary>");
            sb.AppendLine("        ''' <param name=\"extent\">The extent.</param>");
            sb.AppendLine("        ''' <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>");
            sb.AppendLine("        Public Overrides Function GetView(extent As EntitySetBase) As DbMappingView");
            sb.AppendLine("            If extent Is Nothing Then");
            sb.AppendLine("                Throw New ArgumentNullException(\"extent\")");
            sb.AppendLine("            End If");
            sb.AppendLine();
            sb.AppendLine("            Dim extentName = extent.EntityContainer.Name & \".\" & extent.Name");

            var index = 0;
            foreach (var view in sortedViews)
            {
                sb.AppendLine();
                sb.Append("            If extentName = \"").Append(view.Key).AppendLine("\" Then");
                sb.Append("                Return GetView").Append(index).AppendLine("()");
                sb.AppendLine("            End If");
                index++;
            }

            sb.AppendLine();
            sb.AppendLine("            Return Nothing");
            sb.AppendLine("        End Function");

            index = 0;
            foreach (var view in sortedViews)
            {
                var entitySql = string.Join(
                    "\" & vbCrLf &\r\n                \"",
                    view.Value.Split(new[] { "\r\n", "\n" }, System.StringSplitOptions.None));

                sb.AppendLine();
                sb.AppendLine("        ''' <summary>");
                sb.Append("        ''' Gets the view for ").Append(view.Key).AppendLine(".");
                sb.AppendLine("        ''' </summary>");
                sb.AppendLine("        ''' <returns>The mapping view.</returns>");
                sb.Append("        Private Shared Function GetView").Append(index).AppendLine("() As DbMappingView");
                sb.AppendLine("            Return New DbMappingView(");
                sb.Append("                \"").Append(entitySql).AppendLine("\")");
                sb.AppendLine("        End Function");
                index++;
            }

            sb.AppendLine("    End Class");
            sb.AppendLine("End Namespace");

            return sb.ToString();
        }
    }
}
